# Загрузка Pandas и очистка данных

In [1]:
import pandas as pd
import numpy as np
from collections import Counter
import datetime as dt

In [2]:
df = pd.read_csv('main_task_new.csv')
pd.set_option('display.max_columns', None)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Restaurant_id      40000 non-null  object
 1   City               40000 non-null  object
 2   Cuisine Style      30717 non-null  object
 3   Ranking            40000 non-null  float64
 4   Rating             40000 non-null  float64
 5   Price Range        26114 non-null  object
 6   Number of Reviews  37457 non-null  float64
 7   Reviews            40000 non-null  object
 8   URL_TA             40000 non-null  object
 9   ID_TA              40000 non-null  object
dtypes: float64(3), object(7)
memory usage: 3.1+ MB

In [3]:
df.head(20)

,Restaurant_id,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
0,id_5569,Paris,"['European', 'French', 'International']",5570.0,3.5,$$ - $$$,194.0,"[['Good food at your doorstep', 'A good hotel ...",/Restaurant_Review-g187147-d1912643-Reviews-R_...,d1912643
1,id_1535,Stockholm,NaN,1537.0,4.0,NaN,10.0,"[['Unique cuisine', 'Delicious Nepalese food']...",/Restaurant_Review-g189852-d7992032-Reviews-Bu...,d7992032
2,id_352,London,"['Japanese', 'Sushi', 'Asian', 'Grill', 'Veget...",353.0,4.5,$$$$,688.0,"[['Catch up with friends', 'Not exceptional'],...",/Restaurant_Review-g186338-d8632781-Reviews-RO...,d8632781
3,id_3456,Berlin,NaN,3458.0,5.0,NaN,3.0,"[[], []]",/Restaurant_Review-g187323-d1358776-Reviews-Es...,d1358776
4,id_615,Munich,"['German', 'Central European', 'Vegetarian Fri...",621.0,4.0,$$ - $$$,84.0,"[['Best place to try a Bavarian food', 'Nice b...",/Restaurant_Review-g187309-d6864963-Reviews-Au...,d6864963
5,id_1418,Oporto,NaN,1419.0,3.0,NaN,2.0,"[['There are better 3 star hotel bars', 'Amazi...",/Restaurant_Review-g189180-d12503536-Reviews-D...,d12503536
6,id_1720,Milan,"['Italian', 'Pizza']",1722.0,4.0,$,50.0,"[['Excellent simple local eatery.', 'Excellent...",/Restaurant_Review-g187849-d5808504-Reviews-Pi...,d5808504
7,id_825,Bratislava,['Italian'],826.0,3.0,NaN,9.0,"[['Wasting of money', 'excellent cuisine'], ['...",/Restaurant_Review-g274924-d3199765-Reviews-Ri...,d3199765
8,id_2690,Vienna,NaN,2692.0,4.0,NaN,NaN,"[[], []]",/Restaurant_Review-g190454-d12845029-Reviews-G...,d12845029
9,id_4209,Rome,"['Italian', 'Pizza', 'Fast Food']",4210.0,4.0,$,55.0,"[['Clean efficient staff', 'Nice little pizza ...",/Restaurant_Review-g187791-d8020681-Reviews-Qu...,d8020681
10,id_6578,Barcelona,NaN,6579.0,3.0,NaN,6.0,"[[], []]",/Restaurant_Review-g187497-d10696479-Reviews-R...,d10696479
11,id_5312,London,"['Italian', 'Pizza', 'Vegetarian Friendly']",5321.0,4.0,$$ - $$$,42.0,"[['Not bad for Canary Wharf', 'To be a pilgrim...",/Restaurant_Review-g186338-d12402429-Reviews-P...,d12402429
12,id_4066,London,"['Italian', 'Pizza', 'Vegetarian Friendly', 'G...",4073.0,3.5,$$ - $$$,286.0,"[['Great service, good za', 'Lovely, relaxed a...",/Restaurant_Review-g186338-d2259559-Reviews-Ma...,d2259559
13,id_4637,Berlin,"['Vegetarian Friendly', 'Gluten Free Options']",4639.0,4.5,$$ - $$$,10.0,"[['What a great spot!', 'Healthy superfoods, v...",/Restaurant_Review-g187323-d12107166-Reviews-L...,d12107166
14,id_4773,Madrid,"['Mediterranean', 'Spanish', 'Healthy']",4776.0,4.0,$$ - $$$,7.0,"[[], []]",/Restaurant_Review-g187514-d10859423-Reviews-B...,d10859423
15,id_1401,Dublin,['Cafe'],1405.0,4.0,$$ - $$$,28.0,"[['Lovely food', 'Great coffee'], ['12/01/2017...",/Restaurant_Review-g186605-d6633059-Reviews-Gr...,d6633059
16,id_5257,Berlin,"['Japanese', 'Asian', 'Thai', 'Vietnamese']",5259.0,4.0,NaN,3.0,"[['This is a real hidden Sushi-gem'], ['04/12/...",/Restaurant_Review-g187323-d10266473-Reviews-A...,d10266473
17,id_11121,London,"['Bar', 'Pub']",11131.0,4.5,$$ - $$$,7.0,"[['gin tour venue', 'Gin Tour'], ['02/28/2017'...",/Restaurant_Review-g186338-d8659568-Reviews-46...,d8659568
18,id_3127,Berlin,['German'],3129.0,4.0,$$ - $$$,12.0,"[['Nice stay, very good hotel', 'great residen...",/Restaurant_Review-g187323-d3702312-Reviews-Al...,d3702312
19,id_2791,Brussels,['Chinese'],2792.0,3.0,$$ - $$$,12.0,"[['Seriously, is this a restaurant?', 'Not tha...",/Restaurant_Review-g947638-d8155327-Reviews-Ho...,d8155327

# Ваш код по очистке данных и генерации новых признаков.
При необходимости добавьте ячейки

In [4]:
df['Price Range'].value_counts()

$$ - $$$    18412
$            6279
$$$$         1423
Name: Price Range, dtype: int64

Преобразуем Price Range и пустые значения заменяем средним

In [5]:
def range_changer(row):
    if row['Price Range'] == '$':
        return 1
    elif  row['Price Range'] == '$$ - $$$':
        return 2
    elif  row['Price Range'] == '$$$$':
        return 3
    else:
        return None
    
df['price_range'] = df.apply(lambda row: range_changer(row), axis=1)

df['price_range'] = df['price_range'].fillna(np.mean(df['price_range']))
df[['price_range']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   price_range  40000 non-null  float64
dtypes: float64(1)
memory usage: 312.6 KB

Преобразуем City в dummies

In [6]:
dummies_city = pd.get_dummies(df.City)
dummies_city.head()

,Amsterdam,Athens,Barcelona,Berlin,Bratislava,Brussels,Budapest,Copenhagen,Dublin,Edinburgh,Geneva,Hamburg,Helsinki,Krakow,Lisbon,Ljubljana,London,Luxembourg,Lyon,Madrid,Milan,Munich,Oporto,Oslo,Paris,Prague,Rome,Stockholm,Vienna,Warsaw,Zurich
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

Преобразуем string Cuisine Style в list

In [7]:
df['Cuisine Style'] = df['Cuisine Style'].str.strip('[]').str.replace(' ', '').str.split(',')

In [8]:
df['Cuisine Style'] = df['Cuisine Style'].fillna(0)

In [9]:
df['Cuisine Style']

0                  ['European', 'French', 'International']
1                                                        0
2        ['Japanese', 'Sushi', 'Asian', 'Grill', 'Veget...
3                                                        0
4        ['German', 'CentralEuropean', 'VegetarianFrien...
                               ...
39995    ['Italian', 'VegetarianFriendly', 'VeganOption...
39996    ['French', 'American', 'Bar', 'European', 'Veg...
39997                                ['Japanese', 'Sushi']
39998    ['Polish', 'European', 'EasternEuropean', 'Cen...
39999                                          ['Spanish']
Name: Cuisine Style, Length: 40000, dtype: object

In [10]:
# kolichestvo kuhon'

In [11]:
cousine_list = []
for row in df['Cuisine Style']:
    if row == 0:
        None
    else:
        for element in row:
            #element = element.replace(' ', '')
            cousine_list.append(element) 

print('unique', len(set(cousine_list)))
Counter(cousine_list).most_common()

unique 125

[("'VegetarianFriendly'", 11189),
 ("'European'", 10060),
 ("'Mediterranean'", 6277),
 ("'Italian'", 5964),
 ("'VeganOptions'", 4486),
 ("'GlutenFreeOptions'", 4113),
 ("'Bar'", 3297),
 ("'French'", 3190),
 ("'Asian'", 3011),
 ("'Pizza'", 2849),
 ("'Spanish'", 2798),
 ("'Pub'", 2449),
 ("'Cafe'", 2325),
 ("'FastFood'", 1705),
 ("'British'", 1595),
 ("'International'", 1584),
 ("'Seafood'", 1505),
 ("'Japanese'", 1464),
 ("'CentralEuropean'", 1393),
 ("'American'", 1315),
 ("'Sushi'", 1156),
 ("'Chinese'", 1145),
 ("'Portuguese'", 1107),
 ("'Indian'", 1041),
 ("'MiddleEastern'", 782),
 ("'Thai'", 743),
 ("'WineBar'", 697),
 ("'German'", 662),
 ("'Healthy'", 620),
 ("'Greek'", 604),
 ("'Halal'", 598),
 ("'Czech'", 595),
 ("'Fusion'", 577),
 ("'Steakhouse'", 573),
 ("'Barbecue'", 555),
 ("'Contemporary'", 523),
 ("'Vietnamese'", 513),
 ("'EasternEuropean'", 496),
 ("'Soups'", 494),
 ("'Grill'", 490),
 ("'Gastropub'", 471),
 ("'Mexican'", 445),
 ("'Turkish'", 444),
 ("'Delicatessen'", 392),
 ("'Austrian'", 380),
 ("'SouthAmerican'", 372),
 ("'Polish'", 365),
 ("'Hungarian'", 352),
 ("'Scandinavian'", 342),
 ("'Lebanese'", 329),
 ("'Latin'", 302),
 ("'Diner'", 295),
 ("'Dutch'", 294),
 ("'Irish'", 284),
 ("'Belgian'", 270),
 ("'StreetFood'", 263),
 ("'BrewPub'", 225),
 ("'Swiss'", 178),
 ("'Danish'", 177),
 ("'Swedish'", 171),
 ("'Argentinean'", 169),
 ("'Korean'", 167),
 ("'Scottish'", 163),
 ("'African'", 154),
 ("'Moroccan'", 141),
 ("'CentralAmerican'", 135),
 ("'Brazilian'", 127),
 ("'Pakistani'", 123),
 ("'Peruvian'", 94),
 ("'Caribbean'", 93),
 ("'Nepali'", 83),
 ("'Balti'", 83),
 ("'Bangladeshi'", 76),
 ("'Norwegian'", 75),
 ("'Israeli'", 74),
 ("'Slovenian'", 68),
 ("'Indonesian'", 59),
 ("'Russian'", 58),
 ("'Persian'", 53),
 ("'Arabic'", 51),
 ("'Kosher'", 48),
 ("'Ethiopian'", 42),
 ("'Venezuelan'", 40),
 ("'Malaysian'", 31),
 ("'Croatian'", 27),
 ("'Jamaican'", 25),
 ("'SriLankan'", 25),
 ("'Tibetan'", 24),
 ("'Australian'", 24),
 ("'Cuban'", 23),
 ("'Taiwanese'", 22),
 ("'Afghani'", 22),
 ("'Hawaiian'", 21),
 ("'Tunisian'", 21),
 ("'Egyptian'", 20),
 ("'Colombian'", 20),
 ("'Cambodian'", 20),
 ("'Cajun&Creole'", 20),
 ("'Singaporean'", 19),
 ("'Ukrainian'", 18),
 ("'Southwestern'", 17),
 ("'Georgian'", 17),
 ("'Mongolian'", 14),
 ("'Armenian'", 14),
 ("'CentralAsian'", 12),
 ("'Filipino'", 12),
 ("'MinorityChinese'", 11),
 ("'Romanian'", 10),
 ("'Chilean'", 8),
 ("'Albanian'", 8),
 ("'NewZealand'", 6),
 ("'Uzbek'", 5),
 ("'Canadian'", 5),
 ("'Ecuadorean'", 4),
 ("'Caucasian'", 4),
 ("'NativeAmerican'", 4),
 ("'Polynesian'", 2),
 ("'Azerbaijani'", 2),
 ("'Fujian'", 2),
 ("'Welsh'", 2),
 ("'Salvadoran'", 1),
 ("'Yunnan'", 1),
 ("'Xinjiang'", 1),
 ("'Burmese'", 1),
 ("'Latvian'", 1)]

Добавляем новый столбец с количеством видов кухань в ресторане

In [12]:
def cousine_count(row):
    if row['Cuisine Style'] != 0:
        count = len(row['Cuisine Style'])
        return count
    else:
        return 1

df['cousine_count'] = df.apply(lambda row: cousine_count(row), axis=1)
df['cousine_count'].mean()

2.6224

In [13]:
df['cousine_count']

0        3
1        1
2        7
3        1
4        3
        ..
39995    4
39996    5
39997    2
39998    5
39999    1
Name: cousine_count, Length: 40000, dtype: int64

In [14]:
df['is_multiple_cousine'] = df['cousine_count'].apply(lambda x: 1 if x > 1 else 0)
df['is_multiple_cousine']

0        1
1        0
2        1
3        0
4        1
        ..
39995    1
39996    1
39997    1
39998    1
39999    0
Name: is_multiple_cousine, Length: 40000, dtype: int64

In [15]:
df['Cuisine Style']

0                  ['European', 'French', 'International']
1                                                        0
2        ['Japanese', 'Sushi', 'Asian', 'Grill', 'Veget...
3                                                        0
4        ['German', 'CentralEuropean', 'VegetarianFrien...
                               ...
39995    ['Italian', 'VegetarianFriendly', 'VeganOption...
39996    ['French', 'American', 'Bar', 'European', 'Veg...
39997                                ['Japanese', 'Sushi']
39998    ['Polish', 'European', 'EasternEuropean', 'Cen...
39999                                          ['Spanish']
Name: Cuisine Style, Length: 40000, dtype: object

Преобразуем Cuisine Style в dummies

In [16]:
s = df['Cuisine Style']
dummies_cousine = pd.get_dummies(s.apply(pd.Series).stack()).sum(level=0)
dummies_cousine.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40000 entries, 0 to 39999
Columns: 126 entries, 0.0 to 'Yunnan'
dtypes: uint8(126)
memory usage: 5.1 MB

In [17]:
df.describe()

,Ranking,Rating,Number of Reviews,price_range,cousine_count,is_multiple_cousine
count,40000.000000,40000.000000,37457.000000,40000.000000,40000.000000,40000.000000
mean,3676.028525,3.993037,124.825480,1.814046,2.622400,0.586325
std,3708.749567,0.668417,295.666352,0.412286,1.817292,0.492498
min,1.000000,1.000000,2.000000,1.000000,1.000000,0.000000
25%,973.000000,3.500000,9.000000,1.814046,1.000000,0.000000
50%,2285.000000,4.000000,33.000000,1.814046,2.000000,1.000000
75%,5260.000000,4.500000,115.000000,2.000000,4.000000,1.000000
max,16444.000000,5.000000,9660.000000,3.000000,21.000000,1.000000

Заполняем пустые Number of Reviews

In [18]:
df['Number of Reviews'] = df['Number of Reviews'].fillna(np.median(df['Number of Reviews'].dropna()))

Создаём отдельный столбик только для отзывов и проверяем на положительные и отрицательные отзывы

In [19]:
df.Reviews = df.Reviews.str.strip('[]').str.replace('[','').str.replace(']','').str.split(',')

<ipython-input-19-43cc67cf024b>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df.Reviews = df.Reviews.str.strip('[]').str.replace('[','').str.replace(']','').str.split(',')

In [20]:
df.Reviews[0][1][4]

'g'

In [21]:
# Отдельный столбик только для текста отзывов
reviews = []
for list1 in df['Reviews']:
    reviews.append(list1[0:2])

df['reviews'] = pd.Series(reviews)

In [22]:
df['reviews'][0][1]

" 'A good hotel restaurant'"

In [23]:
# Bсе отзывы по рестарану в одну строчку и разделяем на отдельные слова
row_all = list()

for row in df['reviews']:
    row_t = []
    row_t = row[0].lower().split(' ') + row[1].lower().split(' ')
    row_all.append(row_t)
    row_t
    
df['reviews_list'] = pd.Series(row_all)
df['reviews_list']

0        ['good, food, at, your, doorstep', , 'a, good,...
1        ['unique, cuisine', , 'delicious, nepalese, fo...
2        ['catch, up, with, friends', , 'not, exception...
3                                                   [, , ]
4        ['best, place, to, try, a, bavarian, food', , ...
                               ...
39995    ['the, real, italian, experience!', , 'wonderf...
39996    ['parisian, atmosphere', , 'bit, pricey, but, ...
39997    ['good, by, swedish, standards', , 'a, hidden,...
39998    ['underground, restaurant', , 'oldest, restaur...
39999                  ['average', , 'nice, an, informal']
Name: reviews_list, Length: 40000, dtype: object

In [24]:
# Проверяем в каких коментариях есть положительные или отрицательные слова

good_words = ['good', 'excellent', 'tasty', 'best', 'nice', 'beautiful', 'unique', 'great', 'lovely', 'brilliant']
bad_words = ['not', 'bad', 'seriously',"'don't'", 'horrible', 'ok', 'terrible', 'but', 'disappointed', 'enough']
is_good = []
is_bad = []

for review in df['reviews_list']:
    for word in review:
        if word in good_words:
            is_good.append(1)
        else:
            is_good.append(0)
        if word in bad_words:
            is_bad.append(1)
        else:
            is_bad.append(0)
                
df['is_good'] = pd.Series(is_good)      
df['is_bad'] = pd.Series(is_bad)

Создаём отдельный столбец для даты отзывов и вычисляем как давно был написан отзыв

In [25]:
dates = []
for list1 in df['Reviews']:
    if len(list1) == 4:
        date = list1[-2:]
    elif len(list1) in [2, 3]:
        date = list1[-1]
    else:
        date = list1[-2:]
    dates.append(date)

df['dates'] = pd.Series(dates)
#print(dt.datetime.strptime(df['dates'][0][0][2:-1], '%m/%d/%Y'))
df['dates']

0        [ '12/31/2017',  '11/20/2017']
1        [ '07/06/2017',  '06/19/2016']
2        [ '01/08/2018',  '01/06/2018']
3
4        [ '11/18/2017',  '02/19/2017']
                      ...
39995    [ '12/16/2017',  '11/12/2017']
39996    [ '12/21/2017',  '12/12/2017']
39997    [ '11/03/2016',  '04/12/2008']
39998    [ '07/11/2017',  '06/18/2017']
39999    [ '01/31/2016',  '07/04/2012']
Name: dates, Length: 40000, dtype: object

In [26]:
# находим дату из последнего столбика
last_date = []

for row in df['dates']:
    dates_diff = []
    if len(row) == 2:
        last_date.append(dt.datetime.strptime(row[-1][2:-1], '%m/%d/%Y'))
    else:
        last_date.append(None)

last_date

[datetime.datetime(2017, 11, 20, 0, 0),
 datetime.datetime(2016, 6, 19, 0, 0),
 datetime.datetime(2018, 1, 6, 0, 0),
 None,
 datetime.datetime(2017, 2, 19, 0, 0),
 datetime.datetime(2017, 5, 31, 0, 0),
 datetime.datetime(2017, 11, 5, 0, 0),
 datetime.datetime(2012, 6, 13, 0, 0),
 None,
 datetime.datetime(2017, 3, 27, 0, 0),
 None,
 datetime.datetime(2017, 11, 22, 0, 0),
 datetime.datetime(2017, 12, 27, 0, 0),
 datetime.datetime(2017, 5, 30, 0, 0),
 None,
 datetime.datetime(2017, 9, 14, 0, 0),
 None,
 datetime.datetime(2016, 10, 31, 0, 0),
 datetime.datetime(2016, 10, 21, 0, 0),
 datetime.datetime(2015, 8, 13, 0, 0),
 datetime.datetime(2017, 12, 4, 0, 0),
 None,
 datetime.datetime(2017, 4, 29, 0, 0),
 datetime.datetime(2017, 10, 5, 0, 0),
 datetime.datetime(2017, 5, 9, 0, 0),
 None,
 None,
 None,
 None,
 None,
 datetime.datetime(2017, 7, 7, 0, 0),
 datetime.datetime(2017, 1, 3, 0, 0),
 datetime.datetime(2015, 10, 26, 0, 0),
 None,
 datetime.datetime(2016, 7, 17, 0, 0),
 None,
 datetime.datetime(2013, 12, 2, 0, 0),
 None,
 None,
 None,
 None,
 datetime.datetime(2017, 7, 29, 0, 0),
 datetime.datetime(2017, 6, 29, 0, 0),
 datetime.datetime(2017, 12, 10, 0, 0),
 None,
 datetime.datetime(2017, 2, 5, 0, 0),
 None,
 datetime.datetime(2018, 2, 14, 0, 0),
 datetime.datetime(2017, 12, 2, 0, 0),
 datetime.datetime(2017, 11, 16, 0, 0),
 datetime.datetime(2017, 12, 12, 0, 0),
 datetime.datetime(2017, 9, 17, 0, 0),
 None,
 datetime.datetime(2017, 10, 6, 0, 0),
 datetime.datetime(2018, 1, 5, 0, 0),
 None,
 None,
 None,
 datetime.datetime(2017, 3, 23, 0, 0),
 None,
 datetime.datetime(2017, 9, 24, 0, 0),
 None,
 datetime.datetime(2016, 5, 17, 0, 0),
 datetime.datetime(2018, 1, 7, 0, 0),
 datetime.datetime(2018, 1, 5, 0, 0),
 datetime.datetime(2016, 10, 8, 0, 0),
 datetime.datetime(2017, 10, 20, 0, 0),
 datetime.datetime(2016, 10, 18, 0, 0),
 None,
 datetime.datetime(2017, 1, 7, 0, 0),
 datetime.datetime(2015, 9, 29, 0, 0),
 None,
 datetime.datetime(2018, 1, 7, 0, 0),
 None,
 datetime.datetime(2017, 2, 21, 0, 0),
 datetime.datetime(2015, 3, 21, 0, 0),
 datetime.datetime(2017, 11, 21, 0, 0),
 datetime.datetime(2017, 6, 25, 0, 0),
 None,
 datetime.datetime(2018, 1, 3, 0, 0),
 datetime.datetime(2017, 4, 14, 0, 0),
 datetime.datetime(2016, 10, 25, 0, 0),
 datetime.datetime(2017, 10, 9, 0, 0),
 datetime.datetime(2016, 9, 20, 0, 0),
 datetime.datetime(2017, 9, 24, 0, 0),
 datetime.datetime(2015, 6, 15, 0, 0),
 datetime.datetime(2016, 8, 14, 0, 0),
 datetime.datetime(2016, 9, 20, 0, 0),
 datetime.datetime(2017, 12, 30, 0, 0),
 datetime.datetime(2017, 3, 11, 0, 0),
 None,
 datetime.datetime(2016, 10, 31, 0, 0),
 datetime.datetime(2017, 7, 5, 0, 0),
 datetime.datetime(2017, 5, 27, 0, 0),
 datetime.datetime(2017, 7, 3, 0, 0),
 datetime.datetime(2017, 12, 18, 0, 0),
 datetime.datetime(2016, 8, 14, 0, 0),
 datetime.datetime(2016, 10, 28, 0, 0),
 datetime.datetime(2017, 3, 7, 0, 0),
 datetime.datetime(2017, 6, 22, 0, 0),
 None,
 datetime.datetime(2017, 6, 27, 0, 0),
 None,
 datetime.datetime(2017, 9, 11, 0, 0),
 None,
 datetime.datetime(2017, 4, 20, 0, 0),
 datetime.datetime(2015, 4, 17, 0, 0),
 datetime.datetime(2016, 12, 22, 0, 0),
 None,
 datetime.datetime(2016, 1, 30, 0, 0),
 datetime.datetime(2016, 8, 19, 0, 0),
 None,
 datetime.datetime(2018, 1, 5, 0, 0),
 datetime.datetime(2013, 12, 3, 0, 0),
 datetime.datetime(2016, 12, 17, 0, 0),
 None,
 datetime.datetime(2016, 8, 11, 0, 0),
 datetime.datetime(2017, 10, 4, 0, 0),
 None,
 datetime.datetime(2017, 7, 16, 0, 0),
 datetime.datetime(2017, 4, 28, 0, 0),
 None,
 datetime.datetime(2017, 9, 5, 0, 0),
 datetime.datetime(2017, 2, 25, 0, 0),
 datetime.datetime(2017, 11, 28, 0, 0),
 datetime.datetime(2016, 11, 24, 0, 0),
 datetime.datetime(2017, 11, 18, 0, 0),
 None,
 datetime.datetime(2017, 11, 19, 0, 0),
 None,
 datetime.datetime(2017, 10, 4, 0, 0),
 datetime.datetime(2015, 6, 1, 0, 0),
 datetime.datetime(2017, 7, 14, 0, 0),
 None,
 datetime.datetime(2017, 11, 19, 0, 0),
 datetime.datetime(2017, 7, 12, 0, 0),
 datetime.datetime(2017, 3, 12, 0, 0),
 datetime.datetime(2015, 9, 18, 0, 0),
 None,
 datetime.datetime(2018, 1, 3, 0, 0),
 datetime.datetime(2016, 6, 9, 0, 0),
 datetime.datetime(2015, 8, 29, 0, 0),
 datetime.datetime(2017, 12, 11, 0, 0),
 None,
 datetime.datetime(2016, 9, 20, 0, 0),
 datetime.datetime(2017, 11, 19, 0, 0),
 datetime.datetime(2017, 9, 19, 0, 0),
 None,
 datetime.datetime(2017, 10, 9, 0, 0),
 datetime.datetime(2017, 8, 5, 0, 0),
 datetime.datetime(2017, 1, 1, 0, 0),
 datetime.datetime(2017, 5, 9, 0, 0),
 None,
 datetime.datetime(2017, 12, 31, 0, 0),
 datetime.datetime(2017, 6, 2, 0, 0),
 None,
 None,
 None,
 datetime.datetime(2015, 4, 30, 0, 0),
 datetime.datetime(2017, 11, 30, 0, 0),
 datetime.datetime(2017, 10, 5, 0, 0),
 None,
 datetime.datetime(2017, 11, 5, 0, 0),
 datetime.datetime(2017, 11, 8, 0, 0),
 None,
 datetime.datetime(2017, 9, 25, 0, 0),
 datetime.datetime(2017, 11, 8, 0, 0),
 None,
 datetime.datetime(2017, 12, 3, 0, 0),
 datetime.datetime(2016, 7, 6, 0, 0),
 datetime.datetime(2017, 10, 7, 0, 0),
 datetime.datetime(2017, 6, 13, 0, 0),
 datetime.datetime(2017, 3, 10, 0, 0),
 datetime.datetime(2017, 10, 30, 0, 0),
 None,
 None,
 None,
 datetime.datetime(2017, 9, 19, 0, 0),
 datetime.datetime(2017, 1, 23, 0, 0),
 datetime.datetime(2016, 9, 2, 0, 0),
 datetime.datetime(2017, 1, 19, 0, 0),
 datetime.datetime(2018, 1, 2, 0, 0),
 datetime.datetime(2017, 4, 13, 0, 0),
 datetime.datetime(2011, 12, 9, 0, 0),
 datetime.datetime(2017, 10, 14, 0, 0),
 None,
 None,
 None,
 datetime.datetime(2017, 6, 26, 0, 0),
 None,
 datetime.datetime(2017, 10, 8, 0, 0),
 datetime.datetime(2017, 11, 19, 0, 0),
 datetime.datetime(2016, 8, 20, 0, 0),
 datetime.datetime(2018, 1, 5, 0, 0),
 datetime.datetime(2017, 9, 24, 0, 0),
 None,
 datetime.datetime(2018, 1, 4, 0, 0),
 datetime.datetime(2017, 12, 24, 0, 0),
 datetime.datetime(2017, 5, 5, 0, 0),
 None,
 datetime.datetime(2017, 12, 31, 0, 0),
 datetime.datetime(2017, 11, 1, 0, 0),
 None,
 None,
 datetime.datetime(2017, 9, 23, 0, 0),
 datetime.datetime(2017, 11, 13, 0, 0),
 datetime.datetime(2017, 3, 11, 0, 0),
 datetime.datetime(2017, 6, 22, 0, 0),
 datetime.datetime(2017, 8, 7, 0, 0),
 None,
 datetime.datetime(2017, 9, 30, 0, 0),
 datetime.datetime(2017, 3, 24, 0, 0),
 datetime.datetime(2017, 8, 22, 0, 0),
 datetime.datetime(2017, 12, 13, 0, 0),
 datetime.datetime(2017, 6, 21, 0, 0),
 datetime.datetime(2016, 1, 13, 0, 0),
 None,
 None,
 datetime.datetime(2015, 12, 21, 0, 0),
 datetime.datetime(2015, 1, 21, 0, 0),
 datetime.datetime(2017, 6, 13, 0, 0),
 None,
 None,
 None,
 datetime.datetime(2017, 11, 30, 0, 0),
 None,
 None,
 datetime.datetime(2017, 3, 25, 0, 0),
 None,
 None,
 None,
 datetime.datetime(2017, 9, 4, 0, 0),
 datetime.datetime(2017, 7, 9, 0, 0),
 datetime.datetime(2015, 8, 16, 0, 0),
 datetime.datetime(2017, 6, 7, 0, 0),
 None,
 datetime.datetime(2017, 12, 30, 0, 0),
 datetime.datetime(2018, 1, 2, 0, 0),
 datetime.datetime(2017, 5, 19, 0, 0),
 datetime.datetime(2017, 10, 9, 0, 0),
 datetime.datetime(2016, 9, 8, 0, 0),
 datetime.datetime(2016, 12, 19, 0, 0),
 datetime.datetime(2017, 10, 26, 0, 0),
 datetime.datetime(2017, 7, 8, 0, 0),
 datetime.datetime(2016, 11, 16, 0, 0),
 datetime.datetime(2018, 1, 7, 0, 0),
 datetime.datetime(2013, 5, 16, 0, 0),
 None,
 datetime.datetime(2017, 10, 4, 0, 0),
 None,
 datetime.datetime(2017, 6, 12, 0, 0),
 datetime.datetime(2017, 5, 24, 0, 0),
 datetime.datetime(2017, 12, 14, 0, 0),
 datetime.datetime(2017, 12, 22, 0, 0),
 datetime.datetime(2017, 4, 9, 0, 0),
 datetime.datetime(2016, 5, 12, 0, 0),
 datetime.datetime(2015, 2, 9, 0, 0),
 datetime.datetime(2017, 12, 5, 0, 0),
 datetime.datetime(2017, 12, 29, 0, 0),
 None,
 None,
 None,
 datetime.datetime(2017, 7, 21, 0, 0),
 datetime.datetime(2017, 11, 20, 0, 0),
 datetime.datetime(2017, 7, 13, 0, 0),
 None,
 datetime.datetime(2017, 8, 4, 0, 0),
 datetime.datetime(2018, 1, 3, 0, 0),
 datetime.datetime(2017, 9, 25, 0, 0),
 None,
 datetime.datetime(2016, 8, 12, 0, 0),
 datetime.datetime(2017, 8, 15, 0, 0),
 datetime.datetime(2013, 8, 3, 0, 0),
 datetime.datetime(2017, 11, 6, 0, 0),
 datetime.datetime(2016, 10, 8, 0, 0),
 None,
 datetime.datetime(2017, 10, 22, 0, 0),
 None,
 datetime.datetime(2016, 8, 31, 0, 0),
 datetime.datetime(2017, 7, 23, 0, 0),
 datetime.datetime(2017, 11, 12, 0, 0),
 None,
 datetime.datetime(2017, 11, 3, 0, 0),
 datetime.datetime(2017, 8, 21, 0, 0),
 datetime.datetime(2017, 12, 20, 0, 0),
 datetime.datetime(2015, 10, 10, 0, 0),
 datetime.datetime(2017, 10, 7, 0, 0),
 datetime.datetime(2016, 11, 13, 0, 0),
 None,
 datetime.datetime(2017, 12, 22, 0, 0),
 datetime.datetime(2017, 8, 21, 0, 0),
 datetime.datetime(2017, 7, 19, 0, 0),
 None,
 datetime.datetime(2017, 7, 9, 0, 0),
 datetime.datetime(2017, 4, 11, 0, 0),
 datetime.datetime(2017, 10, 13, 0, 0),
 datetime.datetime(2017, 8, 11, 0, 0),
 None,
 datetime.datetime(2017, 11, 18, 0, 0),
 datetime.datetime(2016, 6, 16, 0, 0),
 datetime.datetime(2017, 4, 26, 0, 0),
 datetime.datetime(2017, 10, 31, 0, 0),
 None,
 datetime.datetime(2017, 9, 9, 0, 0),
 None,
 None,
 None,
 datetime.datetime(2017, 3, 8, 0, 0),
 datetime.datetime(2017, 9, 22, 0, 0),
 datetime.datetime(2017, 12, 13, 0, 0),
 datetime.datetime(2017, 11, 27, 0, 0),
 datetime.datetime(2017, 10, 1, 0, 0),
 datetime.datetime(2017, 12, 6, 0, 0),
 datetime.datetime(2017, 4, 11, 0, 0),
 None,
 datetime.datetime(2017, 4, 4, 0, 0),
 datetime.datetime(2016, 12, 25, 0, 0),
 datetime.datetime(2017, 7, 16, 0, 0),
 datetime.datetime(2017, 5, 19, 0, 0),
 datetime.datetime(2016, 8, 13, 0, 0),
 None,
 datetime.datetime(2017, 12, 29, 0, 0),
 datetime.datetime(2017, 5, 26, 0, 0),
 datetime.datetime(2017, 9, 19, 0, 0),
 datetime.datetime(2017, 9, 25, 0, 0),
 None,
 None,
 datetime.datetime(2017, 11, 13, 0, 0),
 datetime.datetime(2017, 8, 4, 0, 0),
 None,
 datetime.datetime(2016, 4, 9, 0, 0),
 datetime.datetime(2017, 11, 10, 0, 0),
 datetime.datetime(2017, 8, 22, 0, 0),
 None,
 datetime.datetime(2017, 9, 16, 0, 0),
 datetime.datetime(2016, 9, 9, 0, 0),
 datetime.datetime(2016, 2, 20, 0, 0),
 datetime.datetime(2017, 1, 14, 0, 0),
 datetime.datetime(2017, 8, 20, 0, 0),
 datetime.datetime(2017, 11, 8, 0, 0),
 datetime.datetime(2017, 12, 22, 0, 0),
 datetime.datetime(2017, 9, 5, 0, 0),
 datetime.datetime(2014, 11, 13, 0, 0),
 datetime.datetime(2013, 10, 12, 0, 0),
 datetime.datetime(2018, 1, 4, 0, 0),
 datetime.datetime(2016, 11, 23, 0, 0),
 datetime.datetime(2016, 1, 26, 0, 0),
 datetime.datetime(2016, 7, 31, 0, 0),
 datetime.datetime(2015, 10, 17, 0, 0),
 datetime.datetime(2017, 11, 4, 0, 0),
 None,
 datetime.datetime(2016, 10, 15, 0, 0),
 datetime.datetime(2018, 1, 10, 0, 0),
 datetime.datetime(2017, 7, 7, 0, 0),
 datetime.datetime(2017, 6, 10, 0, 0),
 datetime.datetime(2017, 12, 29, 0, 0),
 datetime.datetime(2017, 7, 13, 0, 0),
 datetime.datetime(2017, 10, 21, 0, 0),
 None,
 datetime.datetime(2017, 3, 27, 0, 0),
 datetime.datetime(2016, 5, 14, 0, 0),
 None,
 datetime.datetime(2017, 9, 22, 0, 0),
 datetime.datetime(2017, 8, 26, 0, 0),
 datetime.datetime(2017, 4, 29, 0, 0),
 datetime.datetime(2017, 10, 18, 0, 0),
 datetime.datetime(2017, 10, 12, 0, 0),
 None,
 datetime.datetime(2017, 3, 23, 0, 0),
 None,
 datetime.datetime(2016, 9, 13, 0, 0),
 datetime.datetime(2017, 12, 22, 0, 0),
 None,
 datetime.datetime(2015, 9, 14, 0, 0),
 datetime.datetime(2016, 5, 21, 0, 0),
 None,
 None,
 datetime.datetime(2018, 1, 4, 0, 0),
 datetime.datetime(2017, 10, 2, 0, 0),
 datetime.datetime(2017, 5, 3, 0, 0),
 datetime.datetime(2017, 3, 30, 0, 0),
 None,
 None,
 datetime.datetime(2017, 12, 13, 0, 0),
 None,
 datetime.datetime(2016, 3, 3, 0, 0),
 datetime.datetime(2017, 11, 12, 0, 0),
 datetime.datetime(2017, 3, 17, 0, 0),
 datetime.datetime(2017, 9, 26, 0, 0),
 datetime.datetime(2016, 6, 10, 0, 0),
 datetime.datetime(2016, 10, 26, 0, 0),
 datetime.datetime(2017, 9, 19, 0, 0),
 datetime.datetime(2017, 5, 15, 0, 0),
 datetime.datetime(2015, 11, 4, 0, 0),
 datetime.datetime(2013, 1, 14, 0, 0),
 datetime.datetime(2016, 8, 31, 0, 0),
 None,
 datetime.datetime(2012, 11, 4, 0, 0),
 datetime.datetime(2014, 1, 19, 0, 0),
 datetime.datetime(2018, 1, 4, 0, 0),
 datetime.datetime(2017, 8, 3, 0, 0),
 datetime.datetime(2017, 10, 17, 0, 0),
 datetime.datetime(2017, 11, 20, 0, 0),
 datetime.datetime(2017, 7, 29, 0, 0),
 datetime.datetime(2017, 1, 18, 0, 0),
 None,
 datetime.datetime(2017, 5, 31, 0, 0),
 datetime.datetime(2017, 5, 26, 0, 0),
 None,
 datetime.datetime(2017, 12, 28, 0, 0),
 None,
 datetime.datetime(2017, 12, 3, 0, 0),
 datetime.datetime(2017, 12, 16, 0, 0),
 datetime.datetime(2017, 9, 10, 0, 0),
 datetime.datetime(2015, 4, 4, 0, 0),
 datetime.datetime(2017, 12, 21, 0, 0),
 datetime.datetime(2013, 4, 22, 0, 0),
 None,
 None,
 None,
 datetime.datetime(2017, 12, 23, 0, 0),
 datetime.datetime(2017, 10, 19, 0, 0),
 datetime.datetime(2017, 6, 19, 0, 0),
 None,
 None,
 datetime.datetime(2016, 3, 9, 0, 0),
 datetime.datetime(2017, 12, 20, 0, 0),
 None,
 None,
 datetime.datetime(2012, 4, 26, 0, 0),
 datetime.datetime(2018, 1, 4, 0, 0),
 None,
 datetime.datetime(2018, 1, 1, 0, 0),
 datetime.datetime(2016, 9, 12, 0, 0),
 datetime.datetime(2016, 11, 6, 0, 0),
 None,
 datetime.datetime(2017, 3, 1, 0, 0),
 datetime.datetime(2017, 10, 29, 0, 0),
 datetime.datetime(2017, 12, 9, 0, 0),
 datetime.datetime(2016, 7, 27, 0, 0),
 datetime.datetime(2016, 12, 17, 0, 0),
 datetime.datetime(2017, 4, 24, 0, 0),
 None,
 None,
 datetime.datetime(2016, 9, 5, 0, 0),
 datetime.datetime(2018, 1, 1, 0, 0),
 None,
 datetime.datetime(2017, 11, 24, 0, 0),
 datetime.datetime(2014, 11, 8, 0, 0),
 datetime.datetime(2017, 6, 7, 0, 0),
 None,
 datetime.datetime(2017, 12, 13, 0, 0),
 datetime.datetime(2017, 9, 5, 0, 0),
 datetime.datetime(2017, 10, 31, 0, 0),
 datetime.datetime(2012, 2, 19, 0, 0),
 datetime.datetime(2017, 1, 27, 0, 0),
 None,
 datetime.datetime(2017, 5, 8, 0, 0),
 datetime.datetime(2015, 10, 28, 0, 0),
 None,
 None,
 datetime.datetime(2017, 12, 19, 0, 0),
 datetime.datetime(2016, 9, 1, 0, 0),
 datetime.datetime(2018, 1, 4, 0, 0),
 datetime.datetime(2017, 10, 14, 0, 0),
 datetime.datetime(2016, 9, 25, 0, 0),
 None,
 datetime.datetime(2017, 11, 3, 0, 0),
 None,
 datetime.datetime(2014, 11, 9, 0, 0),
 None,
 datetime.datetime(2017, 8, 18, 0, 0),
 None,
 None,
 datetime.datetime(2017, 10, 31, 0, 0),
 datetime.datetime(2017, 9, 10, 0, 0),
 datetime.datetime(2014, 1, 7, 0, 0),
 None,
 datetime.datetime(2017, 9, 2, 0, 0),
 None,
 datetime.datetime(2017, 10, 20, 0, 0),
 None,
 datetime.datetime(2017, 2, 15, 0, 0),
 datetime.datetime(2017, 8, 15, 0, 0),
 datetime.datetime(2017, 11, 29, 0, 0),
 datetime.datetime(2017, 5, 26, 0, 0),
 None,
 datetime.datetime(2012, 5, 25, 0, 0),
 datetime.datetime(2017, 12, 6, 0, 0),
 datetime.datetime(2017, 3, 28, 0, 0),
 None,
 datetime.datetime(2015, 9, 24, 0, 0),
 None,
 datetime.datetime(2018, 1, 3, 0, 0),
 datetime.datetime(2017, 5, 5, 0, 0),
 datetime.datetime(2017, 9, 8, 0, 0),
 datetime.datetime(2012, 9, 4, 0, 0),
 None,
 datetime.datetime(2018, 1, 8, 0, 0),
 datetime.datetime(2017, 9, 22, 0, 0),
 datetime.datetime(2017, 9, 15, 0, 0),
 datetime.datetime(2017, 2, 14, 0, 0),
 datetime.datetime(2017, 2, 9, 0, 0),
 None,
 None,
 datetime.datetime(2016, 4, 3, 0, 0),
 datetime.datetime(2016, 4, 15, 0, 0),
 datetime.datetime(2017, 9, 3, 0, 0),
 datetime.datetime(2016, 6, 20, 0, 0),
 None,
 datetime.datetime(2016, 4, 11, 0, 0),
 datetime.datetime(2017, 9, 10, 0, 0),
 datetime.datetime(2017, 2, 14, 0, 0),
 datetime.datetime(2016, 4, 22, 0, 0),
 datetime.datetime(2017, 6, 11, 0, 0),
 datetime.datetime(2017, 10, 9, 0, 0),
 datetime.datetime(2017, 12, 24, 0, 0),
 None,
 None,
 datetime.datetime(2014, 4, 25, 0, 0),
 datetime.datetime(2017, 5, 16, 0, 0),
 datetime.datetime(2018, 1, 2, 0, 0),
 datetime.datetime(2018, 1, 6, 0, 0),
 datetime.datetime(2017, 11, 10, 0, 0),
 datetime.datetime(2017, 10, 1, 0, 0),
 None,
 datetime.datetime(2015, 5, 1, 0, 0),
 datetime.datetime(2018, 1, 7, 0, 0),
 datetime.datetime(2017, 10, 11, 0, 0),
 None,
 datetime.datetime(2018, 1, 19, 0, 0),
 datetime.datetime(2017, 2, 6, 0, 0),
 datetime.datetime(2018, 1, 21, 0, 0),
 None,
 datetime.datetime(2017, 9, 8, 0, 0),
 datetime.datetime(2016, 11, 15, 0, 0),
 None,
 None,
 datetime.datetime(2017, 2, 6, 0, 0),
 datetime.datetime(2017, 11, 26, 0, 0),
 None,
 datetime.datetime(2018, 1, 5, 0, 0),
 datetime.datetime(2018, 1, 3, 0, 0),
 None,
 datetime.datetime(2017, 7, 5, 0, 0),
 datetime.datetime(2017, 11, 28, 0, 0),
 datetime.datetime(2018, 1, 3, 0, 0),
 datetime.datetime(2017, 3, 1, 0, 0),
 datetime.datetime(2017, 4, 4, 0, 0),
 datetime.datetime(2017, 10, 2, 0, 0),
 datetime.datetime(2017, 8, 11, 0, 0),
 datetime.datetime(2017, 11, 7, 0, 0),
 None,
 datetime.datetime(2015, 7, 6, 0, 0),
 datetime.datetime(2017, 12, 20, 0, 0),
 datetime.datetime(2016, 9, 16, 0, 0),
 datetime.datetime(2017, 2, 12, 0, 0),
 None,
 datetime.datetime(2016, 11, 21, 0, 0),
 None,
 None,
 datetime.datetime(2014, 10, 17, 0, 0),
 None,
 datetime.datetime(2017, 12, 30, 0, 0),
 datetime.datetime(2017, 8, 11, 0, 0),
 None,
 datetime.datetime(2017, 6, 12, 0, 0),
 datetime.datetime(2017, 4, 21, 0, 0),
 None,
 datetime.datetime(2017, 5, 1, 0, 0),
 datetime.datetime(2018, 1, 27, 0, 0),
 datetime.datetime(2017, 12, 28, 0, 0),
 datetime.datetime(2017, 10, 23, 0, 0),
 None,
 datetime.datetime(2017, 8, 25, 0, 0),
 datetime.datetime(2017, 9, 10, 0, 0),
 None,
 datetime.datetime(2017, 12, 21, 0, 0),
 datetime.datetime(2018, 1, 4, 0, 0),
 datetime.datetime(2017, 7, 16, 0, 0),
 None,
 datetime.datetime(2017, 7, 10, 0, 0),
 datetime.datetime(2017, 10, 21, 0, 0),
 datetime.datetime(2017, 6, 14, 0, 0),
 None,
 datetime.datetime(2018, 1, 1, 0, 0),
 datetime.datetime(2016, 8, 21, 0, 0),
 datetime.datetime(2017, 9, 20, 0, 0),
 datetime.datetime(2017, 5, 28, 0, 0),
 datetime.datetime(2016, 9, 10, 0, 0),
 None,
 datetime.datetime(2017, 3, 2, 0, 0),
 datetime.datetime(2017, 9, 11, 0, 0),
 datetime.datetime(2017, 11, 23, 0, 0),
 datetime.datetime(2017, 12, 22, 0, 0),
 None,
 datetime.datetime(2018, 1, 1, 0, 0),
 None,
 datetime.datetime(2016, 8, 8, 0, 0),
 datetime.datetime(2017, 11, 1, 0, 0),
 None,
 datetime.datetime(2017, 9, 19, 0, 0),
 None,
 datetime.datetime(2017, 9, 12, 0, 0),
 datetime.datetime(2016, 11, 1, 0, 0),
 datetime.datetime(2015, 7, 6, 0, 0),
 datetime.datetime(2018, 2, 2, 0, 0),
 datetime.datetime(2014, 10, 13, 0, 0),
 datetime.datetime(2017, 7, 25, 0, 0),
 None,
 datetime.datetime(2017, 10, 6, 0, 0),
 datetime.datetime(2018, 1, 1, 0, 0),
 datetime.datetime(2017, 12, 31, 0, 0),
 datetime.datetime(2017, 5, 26, 0, 0),
 None,
 datetime.datetime(2017, 10, 19, 0, 0),
 datetime.datetime(2017, 5, 16, 0, 0),
 datetime.datetime(2016, 8, 28, 0, 0),
 datetime.datetime(2017, 6, 16, 0, 0),
 datetime.datetime(2017, 11, 17, 0, 0),
 datetime.datetime(2016, 11, 28, 0, 0),
 datetime.datetime(2017, 11, 23, 0, 0),
 datetime.datetime(2017, 7, 7, 0, 0),
 datetime.datetime(2016, 8, 10, 0, 0),
 datetime.datetime(2017, 8, 11, 0, 0),
 datetime.datetime(2017, 12, 12, 0, 0),
 datetime.datetime(2016, 11, 5, 0, 0),
 datetime.datetime(2018, 1, 1, 0, 0),
 datetime.datetime(2017, 4, 17, 0, 0),
 datetime.datetime(2018, 1, 7, 0, 0),
 None,
 None,
 datetime.datetime(2017, 11, 30, 0, 0),
 datetime.datetime(2017, 3, 23, 0, 0),
 datetime.datetime(2017, 6, 29, 0, 0),
 datetime.datetime(2015, 11, 21, 0, 0),
 datetime.datetime(2016, 6, 16, 0, 0),
 datetime.datetime(2017, 12, 16, 0, 0),
 None,
 datetime.datetime(2017, 7, 14, 0, 0),
 datetime.datetime(2017, 9, 10, 0, 0),
 None,
 None,
 datetime.datetime(2014, 8, 16, 0, 0),
 datetime.datetime(2017, 7, 11, 0, 0),
 datetime.datetime(2017, 12, 31, 0, 0),
 None,
 datetime.datetime(2017, 6, 17, 0, 0),
 datetime.datetime(2017, 8, 24, 0, 0),
 datetime.datetime(2017, 6, 7, 0, 0),
 datetime.datetime(2017, 1, 17, 0, 0),
 datetime.datetime(2017, 7, 20, 0, 0),
 datetime.datetime(2017, 12, 24, 0, 0),
 datetime.datetime(2014, 5, 28, 0, 0),
 None,
 None,
 datetime.datetime(2016, 8, 13, 0, 0),
 datetime.datetime(2017, 7, 20, 0, 0),

In [27]:
# Смотрим как давно был оставлен отзыв
today = dt.datetime.today()
day_diff = []
for date in last_date:
    if date != None:
        diff = (today-date).days
        day_diff.append(diff)
    else:
        day_diff.append(None)
        
df['days_since_review'] = pd.Series(day_diff)
df['days_since_review'] = round(df['days_since_review'].fillna(np.mean(df['days_since_review'].dropna())))
df['days_since_review']

0        1437.0
1        1956.0
2        1390.0
3        1706.0
4        1711.0
          ...
39995    1445.0
39996    1415.0
39997    4946.0
39998    1592.0
39999    3402.0
Name: days_since_review, Length: 40000, dtype: float64

In [28]:
# Отдельный столбик только для даты отзывов
dates = []
for list1 in df['Reviews']:
    dates.append(list1[2:4])

df['dates'] = pd.Series(dates)
dt.datetime.strptime(df['dates'][0][0][2:-1], '%m/%d/%Y')

datetime.datetime(2017, 12, 31, 0, 0)

Обьединяем dummies и основной df в одно целое. Заполняем пустые dummies нулями

In [29]:
df = pd.concat([df, dummies_city, dummies_cousine], axis=1)
df = df.fillna(0)
df.head()

,Restaurant_id,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA,price_range,cousine_count,is_multiple_cousine,reviews,reviews_list,is_good,is_bad,dates,days_since_review,Amsterdam,Athens,Barcelona,Berlin,Bratislava,Brussels,Budapest,Copenhagen,Dublin,Edinburgh,Geneva,Hamburg,Helsinki,Krakow,Lisbon,Ljubljana,London,Luxembourg,Lyon,Madrid,Milan,Munich,Oporto,Oslo,Paris,Prague,Rome,Stockholm,Vienna,Warsaw,Zurich,0.0,'Afghani','African','Albanian','American','Arabic','Argentinean','Armenian','Asian','Australian','Austrian','Azerbaijani','Balti','Bangladeshi','Bar','Barbecue','Belgian','Brazilian','BrewPub','British','Burmese','Cafe','Cajun&Creole','Cambodian','Canadian','Caribbean','Caucasian','CentralAmerican','CentralAsian','CentralEuropean','Chilean','Chinese','Colombian','Contemporary','Croatian','Cuban','Czech','Danish','Delicatessen','Diner','Dutch','EasternEuropean','Ecuadorean','Egyptian','Ethiopian','European','FastFood','Filipino','French','Fujian','Fusion','Gastropub','Georgian','German','GlutenFreeOptions','Greek','Grill','Halal','Hawaiian','Healthy','Hungarian','Indian','Indonesian','International','Irish','Israeli','Italian','Jamaican','Japanese','Korean','Kosher','Latin','Latvian','Lebanese','Malaysian','Mediterranean','Mexican','MiddleEastern','MinorityChinese','Mongolian','Moroccan','NativeAmerican','Nepali','NewZealand','Norwegian','Pakistani','Persian','Peruvian','Pizza','Polish','Polynesian','Portuguese','Pub','Romanian','Russian','Salvadoran','Scandinavian','Scottish','Seafood','Singaporean','Slovenian','Soups','SouthAmerican','Southwestern','Spanish','SriLankan','Steakhouse','StreetFood','Sushi','Swedish','Swiss','Taiwanese','Thai','Tibetan','Tunisian','Turkish','Ukrainian','Uzbek','VeganOptions','VegetarianFriendly','Venezuelan','Vietnamese','Welsh','WineBar','Xinjiang','Yunnan'
0,id_5569,Paris,"['European', 'French', 'International']",5570.0,3.5,$$ - $$$,194.0,"['Good food at your doorstep', 'A good hotel ...",/Restaurant_Review-g187147-d1912643-Reviews-R_...,d1912643,2.000000,3,1,"['Good food at your doorstep', 'A good hotel ...","['good, food, at, your, doorstep', , 'a, good,...",0,0,"[ '12/31/2017', '11/20/2017']",1437.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,id_1535,Stockholm,0,1537.0,4.0,0,10.0,"['Unique cuisine', 'Delicious Nepalese food',...",/Restaurant_Review-g189852-d7992032-Reviews-Bu...,d7992032,1.814046,1,0,"['Unique cuisine', 'Delicious Nepalese food']","['unique, cuisine', , 'delicious, nepalese, fo...",0,0,"[ '07/06/2017', '06/19/2016']",1956.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,id_352,London,"['Japanese', 'Sushi', 'Asian', 'Grill', 'Veget...",353.0,4.5,$$$$,688.0,"['Catch up with friends', 'Not exceptional', ...",/Restaurant_Review-g186338-d8632781-Reviews-RO...,d8632781,3.000000,7,1,"['Catch up with friends', 'Not exceptional']","['catch, up, with, friends', , 'not, exception...",0,0,"[ '01/08/2018', '01/06/2018']",1390.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0
3,id_3456,Berlin,0,3458.0,5.0,0,3.0,"[, ]",/Restaurant_Review-g187323-d1358776-Reviews-Es...,d1358776,1.814046,1,0,"[, ]","[, , ]",0,0,[],1706.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,id_615,Munich,"['German', 'CentralEuropean', 'VegetarianFrien...",621.0,4.0,$$ - $$$,84.0,"['Best place to try a Bavarian food', 'Nice b...",/Restaurant_Review-g187309-d6864963-Reviews-Au...,d6864963,2.000000,3,1,"['Best place to try a Bavarian food', 'Nice b...","['best, place, to, try, a, bavarian, food', , ...",0,0,"[ '11/18/2017', '02/19/2017']",1711.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [30]:
df_num_only = df.drop(['Restaurant_id', 'Price Range', 'Cuisine Style', 'City', 'URL_TA', 'ID_TA', 'Reviews', 'reviews', 'reviews_list', 'dates'], axis=1)
df_num_only.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Columns: 166 entries, Ranking to 'Yunnan'
dtypes: float64(5), int64(4), uint8(157)
memory usage: 8.7 MB

# Разбиваем датафрейм на части, необходимые для обучения и тестирования модели

In [31]:
# testing my vers
X = df_num_only.drop(['Rating'], axis = 1)
y = df_num_only['Rating']

In [32]:
# Х - данные с информацией о ресторанах, у - целевая переменная (рейтинги ресторанов)
############## X = df.drop(['Restaurant_id', 'Rating'], axis = 1)
############### y = df['Rating']

In [33]:
# Загружаем специальный инструмент для разбивки:
from sklearn.model_selection import train_test_split

In [34]:
# Наборы данных с меткой "train" будут использоваться для обучения модели, "test" - для тестирования.
# Для тестирования мы будем использовать 25% от исходного датасета.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

# Создаём, обучаем и тестируем модель

In [35]:
# Импортируем необходимые библиотеки:
from sklearn.ensemble import RandomForestRegressor # инструмент для создания и обучения модели
from sklearn import metrics # инструменты для оценки точности модели

In [36]:
# Создаём модель
regr = RandomForestRegressor(n_estimators=100)

# Обучаем модель на тестовом наборе данных
regr.fit(X_train, y_train)

# Используем обученную модель для предсказания рейтинга ресторанов в тестовой выборке.
# Предсказанные значения записываем в переменную y_pred
y_pred = regr.predict(X_test)

In [42]:
# Сравниваем предсказанные значения (y_pred) с реальными (y_test), и смотрим насколько они в среднем отличаются
# Метрика называется Mean Absolute Error (MAE) и показывает среднее отклонение предсказанных значений от фактических.

print('MAE:', round(metrics.mean_absolute_error(y_test, y_pred), 5))

MAE: 0.21102